### ISSUE TITLE
loot not working...no connection?

### ISSUE THREAD

**Issue by baffled-bob** [loot/fallout4#62]
new to this... tried many approaches to repair loot. read most of the bug logs and comments and tried them on my problem. nothing so now below is my latest buglog. and frankly...i don't get it.

[11:32:32.803633] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[11:32:32.881637] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[11:32:34.619736] [warning]: No masterlist present at C:\Users\Gerald\AppData\Local\LOOT\Fallout4\masterlist.yaml
[11:32:38.619965] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[11:32:38.622965] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
[11:33:30.290921] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[11:33:30.291921] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
[11:39:15.322655] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[11:39:15.322655] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)

thought it might be from #882, however after installing visual studio update i still have prob. may have missed other fix though...
Bingo..'the easy fix' program from MS did the deed
thank you for your efforts

**Comment by baffled-bob** [comment]
[11:32:32.803633] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[11:32:32.881637] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[11:32:34.619736] [warning]: No masterlist present at C:\Users\Gerald\AppData\Local\LOOT\Fallout4\masterlist.yaml
[11:32:38.619965] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[11:32:38.622965] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
[11:33:30.290921] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[11:33:30.291921] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)

**Comment by Ortham** [comment]
That's loot/loot#882, see the fix that's given in that issue thread, the release notes, readme and FAQs.
