### ISSUE TITLE
Error Oh No Something Went Wrong

### ISSUE THREAD

**Issue by Snakestone91** [loot/fallout4#63]
I updated loot today and now when I try to run loot for Fallout 4, NV or Skyrim it says no masterlist present. When I try to update masterlist or sort my load order it says something went wrong.

Here is my debuglog:

[04:49:20.358092] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[04:49:20.415095] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[04:49:21.366150] [warning]: Not a Git repository: C:\Users\John\AppData\Local\LOOT\Fallout4
[04:49:29.574619] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[04:49:29.575619] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)

**Comment by insizor** [comment]
I am having this same issue, with the same exact error message. In case there's some minute difference I'm missing, I suppose I'll post it to be safe.

[00:21:02.564313] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[00:21:03.188349] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[00:21:04.335414] [warning]: No masterlist present at C:\Users\Jake\AppData\Local\LOOT\Skyrim\masterlist.yaml
[00:21:12.940907] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[00:21:12.943907] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)

Sorry that I can't offer more info than that! I believe I've used LOOT on this computer before, not sure when things might've gone wrong.

Edit: In exploring (and learning how Github works,) the posts here, this issue seems to be resolved Snakestone! Gotta go here https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in#easy and install this registry edit. This seems to fix this "-17; unknown certificate check failure: libgit2 error" if I'm understanding everything correctly!

Edit2: Yup, just reinstalled the latest LOOT dist (I had rolled back in case it was an issue with a new release) and the easy fix from Microsoft fixed this. Thanks again, Wrinkly!

**Comment by Ortham** [comment]
That's loot/loot#882, see the fix that's given in that issue thread, the release notes, readme and FAQs.
